# Generated by Django 5.2.10 on 2026-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, verbose_name='Mã lớp')),
                ('management_code', models.CharField(max_length=20, verbose_name='Mã QL')),
                ('course_code', models.CharField(max_length=20, verbose_name='Mã HP')),
                ('course_name', models.CharField(max_length=200, verbose_name='Tên học phần')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trường/Viện/Khoa')),
                ('associated_class_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã lớp kèm')),
                ('requires_experiment', models.BooleanField(default=False, verbose_name='Cần TN')),
                ('class_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Loại lớp')),
                ('day', models.IntegerField(verbose_name='Thứ')),
                ('start_time', models.IntegerField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.IntegerField(verbose_name='Giờ kết thúc')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('week_list', models.CharField(max_length=100, verbose_name='Danh sách tuần')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
        ),
    ]
