# Generated by Django 5.2.10 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='associated_class_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã_lớp_kèm'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_code',
            field=models.CharField(max_length=20, verbose_name='Mã_lớp'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='class_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Loại_lớp'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='course_code',
            field=models.CharField(max_length=20, verbose_name='Mã_HP'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='course_name',
            field=models.CharField(max_length=200, verbose_name='Tên_HP'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='end_time',
            field=models.IntegerField(verbose_name='KT'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='management_code',
            field=models.CharField(max_length=20, verbose_name='Mã_QL'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi_chú'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='requires_experiment',
            field=models.BooleanField(default=False, verbose_name='Cần_TN'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='school_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trường_Viện_Khoa'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='start_time',
            field=models.IntegerField(verbose_name='BĐ'),
        ),
        migrations.AlterField(
            model_name='classinfo',
            name='week_list',
            field=models.CharField(max_length=100, verbose_name='Tuần'),
        ),
    ]
