# Generated by Django 5.2.10 on 2026-01-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inputHandler', '0002_alter_classinfo_associated_class_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inputHandler.classinfo')),
            ],
        ),
    ]
